include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    always_specify_types: true
    avoid_print: false
    file_names: false
    avoid_function_literals_in_foreach_calls: false
    constant_identifier_names: false